/**
 * @author Kiku
 *
 * Weather data for each area
 *
 * The order in which each weather is listed for an area is important.
 *
 * The chance value in each object for an area should (usually) sum up to 100.
 */

const weatherData = {
  limsaLominsa: [
    { name: "clouds", chance: 20 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 30 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
  ],
  middleLaNoscea: [
    { name: "clouds", chance: 20 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 20 },
    { name: "wind", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
  ],
  lowerLaNoscea: [
    { name: "clouds", chance: 20 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 20 },
    { name: "wind", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
  ],
  easternLaNoscea: [
    { name: "fog", chance: 5 },
    { name: "clearSkies", chance: 45 },
    { name: "fairSkies", chance: 30 },
    { name: "clouds", chance: 10 },
    { name: "rain", chance: 5 },
    { name: "showers", chance: 5 },
  ],
  westernLaNoscea: [
    { name: "fog", chance: 10 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 20 },
    { name: "clouds", chance: 20 },
    { name: "wind", chance: 10 },
    { name: "gales", chance: 10 },
  ],
  upperLaNoscea: [
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 20 },
    { name: "clouds", chance: 20 },
    { name: "fog", chance: 10 },
    { name: "thunder", chance: 10 },
    { name: "thunderstorms", chance: 10 },
  ],
  outerLaNoscea: [
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 20 },
    { name: "clouds", chance: 20 },
    { name: "fog", chance: 15 },
    { name: "rain", chance: 15 },
  ],
  wolvesDenPier: [
    { name: "clouds", chance: 20 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 30 },
    { name: "fog", chance: 10 },
    { name: "thunderstorms", chance: 10 },
  ],
  mist: [
    { name: "clouds", chance: 20 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 30 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
  ],
  gridania: [
    { name: "rain", chance: 20 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 10 },
    { name: "fairSkies", chance: 15 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 15 },
  ],
  centralShroud: [
    { name: "thunder", chance: 5 },
    { name: "rain", chance: 15 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 10 },
    { name: "fairSkies", chance: 15 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 15 },
  ],
  eastShroud: [
    { name: "thunder", chance: 5 },
    { name: "rain", chance: 15 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 10 },
    { name: "fairSkies", chance: 15 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 15 },
  ],
  southShroud: [
    { name: "fog", chance: 5 },
    { name: "thunderstorms", chance: 5 },
    { name: "thunder", chance: 15 },
    { name: "fog", chance: 5 },
    { name: "clouds", chance: 10 },
    { name: "fairSkies", chance: 30 },
    { name: "clearSkies", chance: 30 },
  ],
  northShroud: [
    { name: "fog", chance: 5 },
    { name: "showers", chance: 5 },
    { name: "rain", chance: 15 },
    { name: "fog", chance: 5 },
    { name: "clouds", chance: 10 },
    { name: "fairSkies", chance: 30 },
    { name: "clearSkies", chance: 30 },
  ],
  theLavenderBeds: [
    { name: "clouds", chance: 5 },
    { name: "rain", chance: 15 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 10 },
    { name: "fairSkies", chance: 15 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 15 },
  ],
  uldah: [
    { name: "clearSkies", chance: 40 },
    { name: "fairSkies", chance: 20 },
    { name: "clouds", chance: 25 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 5 },
  ],
  westernThanalan: [
    { name: "clearSkies", chance: 40 },
    { name: "fairSkies", chance: 20 },
    { name: "clouds", chance: 25 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 5 },
  ],
  centralThanalan: [
    { name: "dustStorms", chance: 15 },
    { name: "clearSkies", chance: 40 },
    { name: "fairSkies", chance: 20 },
    { name: "clouds", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 5 },
  ],
  easternThanalan: [
    { name: "clearSkies", chance: 40 },
    { name: "fairSkies", chance: 20 },
    { name: "clouds", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 5 },
    { name: "showers", chance: 15 },
  ],
  southernThanalan: [
    { name: "heatWaves", chance: 20 },
    { name: "clearSkies", chance: 40 },
    { name: "fairSkies", chance: 20 },
    { name: "clouds", chance: 10 },
    { name: "fog", chance: 10 },
  ],
  northernThanalan: [
    { name: "clearSkies", chance: 5 },
    { name: "fairSkies", chance: 15 },
    { name: "clouds", chance: 30 },
    { name: "fog", chance: 50 },
  ],
  theGoblet: [
    { name: "clearSkies", chance: 40 },
    { name: "fairSkies", chance: 20 },
    { name: "clouds", chance: 25 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 5 },
  ],
  morDhona: [
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 15 },
    { name: "gloom", chance: 30 },
    { name: "clearSkies", chance: 15 },
    { name: "fairSkies", chance: 25 },
  ],
  ishgard: [
    { name: "snow", chance: 60 },
    { name: "fairSkies", chance: 10 },
    { name: "clearSkies", chance: 5 },
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 10 },
  ],
  empyreum: [
    { name: "snow", chance: 5 },
    { name: "fairSkies", chance: 20 },
    { name: "clearSkies", chance: 40 },
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 10 },
  ],
  coerthasCentralHighlands: [
    { name: "blizzard", chance: 20 },
    { name: "snow", chance: 40 },
    { name: "fairSkies", chance: 10 },
    { name: "clearSkies", chance: 5 },
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 10 },
  ],
  coerthasWesternHighlands: [
    { name: "blizzard", chance: 20 },
    { name: "snow", chance: 40 },
    { name: "fairSkies", chance: 10 },
    { name: "clearSkies", chance: 5 },
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 10 },
  ],
  theSeaOfclouds: [
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 30 },
    { name: "clouds", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "wind", chance: 10 },
    { name: "umbralWind", chance: 10 },
  ],
  azysLla: [
    { name: "fairSkies", chance: 35 },
    { name: "clouds", chance: 35 },
    { name: "thunder", chance: 30 },
  ],
  theDravanianForelands: [
    { name: "clouds", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "thunder", chance: 10 },
    { name: "dustStorms", chance: 10 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 30 },
  ],
  theDravanianHinterlands: [
    { name: "clouds", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "showers", chance: 10 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 30 },
  ],
  theChurningMists: [
    { name: "clouds", chance: 10 },
    { name: "gales", chance: 10 },
    { name: "umbralStatic", chance: 20 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 30 },
  ],
  idyllshire: [
    { name: "clouds", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "showers", chance: 10 },
    { name: "clearSkies", chance: 30 },
    { name: "fairSkies", chance: 30 },
  ],
  rhalgrsReach: [
    { name: "clearSkies", chance: 15 },
    { name: "fairSkies", chance: 45 },
    { name: "clouds", chance: 20 },
    { name: "fog", chance: 10 },
    { name: "thunder", chance: 10 },
  ],
  theFringes: [
    { name: "clearSkies", chance: 15 },
    { name: "fairSkies", chance: 45 },
    { name: "clouds", chance: 20 },
    { name: "fog", chance: 10 },
    { name: "thunder", chance: 10 },
  ],
  thePeaks: [
    { name: "clearSkies", chance: 10 },
    { name: "fairSkies", chance: 50 },
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 10 },
    { name: "wind", chance: 10 },
    { name: "dustStorms", chance: 5 },
  ],
  theLochs: [
    { name: "clearSkies", chance: 20 },
    { name: "fairSkies", chance: 40 },
    { name: "clouds", chance: 20 },
    { name: "fog", chance: 10 },
    { name: "thunderstorms", chance: 10 },
  ],
  kugane: [
    { name: "rain", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 20 },
    { name: "fairSkies", chance: 40 },
    { name: "clearSkies", chance: 20 },
  ],
  shirogane: [
    { name: "rain", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 20 },
    { name: "fairSkies", chance: 40 },
    { name: "clearSkies", chance: 20 },
  ],
  theRubySea: [
    { name: "thunder", chance: 10 },
    { name: "wind", chance: 10 },
    { name: "clouds", chance: 15 },
    { name: "fairSkies", chance: 40 },
    { name: "clearSkies", chance: 25 },
  ],
  yanxia: [
    { name: "showers", chance: 5 },
    { name: "rain", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 15 },
    { name: "fairSkies", chance: 40 },
    { name: "clearSkies", chance: 20 },
  ],
  theAzimSteppe: [
    { name: "gales", chance: 5 },
    { name: "wind", chance: 5 },
    { name: "rain", chance: 7 },
    { name: "fog", chance: 8 },
    { name: "clouds", chance: 10 },
    { name: "fairSkies", chance: 40 },
    { name: "clearSkies", chance: 25 },
  ],
  eurekaAnemos: [
    { name: "fairSkies", chance: 30 },
    { name: "gales", chance: 30 },
    { name: "showers", chance: 30 },
    { name: "snow", chance: 10 },
  ],
  eurekaPagos: [
    { name: "clearSkies", chance: 10 },
    { name: "fog", chance: 18 },
    { name: "heatWaves", chance: 18 },
    { name: "snow", chance: 18 },
    { name: "thunder", chance: 18 },
    { name: "blizzard", chance: 18 },
  ],
  eurekaPyros: [
    { name: "fairSkies", chance: 10 },
    { name: "heatWaves", chance: 18 },
    { name: "thunder", chance: 18 },
    { name: "blizzard", chance: 18 },
    { name: "umbralWind", chance: 18 },
    { name: "snow", chance: 18 },
  ],
  eurekaHydatos: [
    { name: "fairSkies", chance: 12 },
    { name: "showers", chance: 22 },
    { name: "gloom", chance: 22 },
    { name: "thunderstorms", chance: 22 },
    { name: "snow", chance: 22 },
  ],
  theCrystarium: [
    { name: "clearSkies", chance: 20 },
    { name: "fairSkies", chance: 40 },
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "thunderstorms", chance: 5 },
  ],
  eulmore: [
    { name: "gales", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 15 },
    { name: "fairSkies", chance: 40 },
    { name: "clearSkies", chance: 15 },
  ],
  lakeland: [
    { name: "clearSkies", chance: 20 },
    { name: "fairSkies", chance: 40 },
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "thunderstorms", chance: 5 },
  ],
  kholusia: [
    { name: "gales", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 15 },
    { name: "fairSkies", chance: 40 },
    { name: "clearSkies", chance: 15 },
  ],
  amhAraeng: [
    { name: "fairSkies", chance: 45 },
    { name: "clouds", chance: 15 },
    { name: "dustStorms", chance: 10 },
    { name: "heatWaves", chance: 10 },
    { name: "clearSkies", chance: 20 },
  ],
  ilMheg: [
    { name: "rain", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 15 },
    { name: "thunderstorms", chance: 10 },
    { name: "clearSkies", chance: 15 },
    { name: "fairSkies", chance: 40 },
  ],
  theRaktikaGreatwood: [
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "umbralWind", chance: 10 },
    { name: "clearSkies", chance: 15 },
    { name: "fairSkies", chance: 40 },
    { name: "clouds", chance: 15 },
  ],
  theTempest: [
    { name: "clouds", chance: 20 },
    { name: "fairSkies", chance: 60 },
    { name: "clearSkies", chance: 20 },
  ],
  radzAtHan: [
    { name: "fog", chance: 10 },
    { name: "rain", chance: 15 },
    { name: "clearSkies", chance: 15 },
    { name: "fairSkies", chance: 40 },
    { name: "clouds", chance: 20 },
  ],
  thavnair: [
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "showers", chance: 5 },
    { name: "clearSkies", chance: 15 },
    { name: "fairSkies", chance: 40 },
    { name: "clouds", chance: 20 },
  ],
  garlemald: [
    { name: "snow", chance: 45 },
    { name: "thunder", chance: 5 },
    { name: "rain", chance: 5 },
    { name: "fog", chance: 5 },
    { name: "clouds", chance: 25 },
    { name: "fairSkies", chance: 10 },
    { name: "clearSkies", chance: 5 },
  ],
  oldSharlayan: [
    { name: "clearSkies", chance: 10 },
    { name: "fairSkies", chance: 40 },
    { name: "clouds", chance: 20 },
    { name: "fog", chance: 15 },
    { name: "snow", chance: 15 },
  ],
  labyrinthos: [
    { name: "clearSkies", chance: 15 },
    { name: "fairSkies", chance: 45 },
    { name: "clouds", chance: 25 },
    { name: "rain", chance: 15 },
  ],
  mareLamentorum: [
    { name: "umbralWind", chance: 15 },
    { name: "moonDust", chance: 15 },
    { name: "fairSkies", chance: 70 },
  ],
  ultimaThule: [
    { name: "astromagneticStorm", chance: 15 },
    { name: "fairSkies", chance: 70 },
    { name: "umbralWind", chance: 15 },
  ],
  elpis: [
    { name: "clouds", chance: 25 },
    { name: "umbralWind", chance: 15 },
    { name: "fairSkies", chance: 45 },
    { name: "clearSkies", chance: 15 },
  ],
  unnamedIsland: [
    { name: "clearSkies", chance: 25 },
    { name: "fairSkies", chance: 45 },
    { name: "clouds", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "fog", chance: 5 },
    { name: "showers", chance: 5 },
  ],
  tuliyollal: [
    { name: "clearSkies", chance: 40 },
    { name: "fairSkies", chance: 40 },
    { name: "clouds", chance: 5 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 5 },
  ],
  urqopacha: [
    { name: "clearSkies", chance: 20 },
    { name: "fairSkies", chance: 30 },
    { name: "clouds", chance: 20 },
    { name: "fog", chance: 10 },
    { name: "wind", chance: 10 },
    { name: "snow", chance: 10 },
  ],
  kozamauka: [
    { name: "clearSkies", chance: 25 },
    { name: "fairSkies", chance: 35 },
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 10 },
    { name: "rain", chance: 10 },
    { name: "showers", chance: 5 },
  ],
  yakTel: [
    { name: "clearSkies", chance: 15 },
    { name: "fairSkies", chance: 40 },
    { name: "clouds", chance: 15 },
    { name: "fog", chance: 15 },
    { name: "rain", chance: 15 },
  ],
  solutionNine: [{ name: "fairSkies", chance: 100 }],
  shaaloani: [
    { name: "clearSkies", chance: 5 },
    { name: "fairSkies", chance: 45 },
    { name: "clouds", chance: 20 },
    { name: "dustStorms", chance: 15 },
    { name: "gales", chance: 15 },
  ],
  heritageFound: [
    { name: "fairSkies", chance: 5 },
    { name: "clouds", chance: 20 },
    { name: "fog", chance: 15 },
    { name: "rain", chance: 5 },
    { name: "thunderstorms", chance: 5 },
    { name: "umbralStatic", chance: 50 },
  ],
  livingMemory: [
    { name: "rain", chance: 10 },
    { name: "fog", chance: 10 },
    { name: "clouds", chance: 20 },
    { name: "fairSkies", chance: 60 },
  ],
  sinusArdorum: [
    { name: "moonDust", chance: 15 },
    { name: "fairSkies", chance: 70 },
    { name: "umbralWind", chance: 15 },
  ],  
};

const areaData = {
  limsaLominsa: "limsa",
  middleLaNoscea: "limsa",
  lowerLaNoscea: "limsa",
  easternLaNoscea: "limsa",
  westernLaNoscea: "limsa",
  upperLaNoscea: "limsa",
  outerLaNoscea: "limsa",
  wolvesDenPier: "limsa",
  mist: "gridania",
  gridania: "gridania",
  centralShroud: "gridania",
  eastShroud: "gridania",
  southShroud: "gridania",
  northShroud: "gridania",
  theLavenderBeds: "gridania",
  uldah: "uldah",
  westernThanalan: "uldah",
  centralThanalan: "uldah",
  easternThanalan: "uldah",
  southernThanalan: "uldah",
  northernThanalan: "uldah",
  theGoblet: "uldah",
  morDhona: "other",
  ishgard: "ishgard",
  empyreum: "ishgard",
  coerthasCentralHighlands: "ishgard",
  coerthasWesternHighlands: "ishgard",
  theSeaOfclouds: "ishgard",
  azysLla: "ishgard",
  theDravanianForelands: "ishgard",
  theDravanianHinterlands: "ishgard",
  theChurningMists: "ishgard",
  idyllshire: "ishgard",
  rhalgrsReach: "gyrabania",
  theFringes: "gyrabania",
  thePeaks: "gyrabania",
  theLochs: "gyrabania",
  kugane: "othard",
  shirogane: "othard",
  theRubySea: "othard",
  yanxia: "othard",
  theAzimSteppe: "othard",
  eurekaAnemos: "other",
  eurekaPagos: "other",
  eurekaPyros: "other",
  eurekaHydatos: "other",
  theCrystarium: "norvrandt",
  eulmore: "norvrandt",
  lakeland: "norvrandt",
  kholusia: "norvrandt",
  amhAraeng: "norvrandt",
  ilMheg: "norvrandt",
  theRaktikaGreatwood: "norvrandt",
  theTempest: "norvrandt",
  radzAtHan: "ilsabard",
  thavnair: "ilsabard",
  garlemald: "ilsabard",
  oldSharlayan: "other",
  labyrinthos: "other",
  mareLamentorum: "other",
  ultimaThule: "other",
  elpis: "other",
  unnamedIsland: "other",
  tuliyollal: "tural",
  urqopacha: "tural",
  kozamauka: "tural",
  yakTel: "tural",
  solutionNine: "tural",
  shaaloani: "tural",
  heritageFound: "tural",
  livingMemory: "other",
  sinusArdorum: "other",
};

const expansionData = {
  aRealmReborn: [
    "limsaLominsa",
    "middleLaNoscea",
    "lowerLaNoscea",
    "easternLaNoscea",
    "westernLaNoscea",
    "upperLaNoscea",
    "outerLaNoscea",
    "wolvesDenPier",
    "mist",
    "gridania",
    "centralShroud",
    "eastShroud",
    "southShroud",
    "northShroud",
    "theLavenderBeds",
    "uldah",
    "westernThanalan",
    "centralThanalan",
    "easternThanalan",
    "southernThanalan",
    "northernThanalan",
    "theGoblet",
    "morDhona",
  ],
  heavensward: [
    "ishgard",
    "empyreum",
    "coerthasCentralHighlands",
    "coerthasWesternHighlands",
    "theSeaOfclouds",
    "azysLla",
    "theDravanianForelands",
    "theDravanianHinterlands",
    "theChurningMists",
    "idyllshire",
  ],
  stormblood: [
    "rhalgrsReach",
    "theFringes",
    "thePeaks",
    "theLochs",
    "kugane",
    "shirogane",
    "theRubySea",
    "yanxia",
    "theAzimSteppe",
    "eurekaAnemos",
    "eurekaPagos",
    "eurekaPyros",
    "eurekaHydatos",
  ],
  shadowbringers: [
    "theCrystarium",
    "eulmore",
    "lakeland",
    "kholusia",
    "amhAraeng",
    "ilMheg",
    "theRaktikaGreatwood",
    "theTempest",
  ],
  endwalker: [
    "radzAtHan",
    "thavnair",
    "garlemald",
    "oldSharlayan",
    "labyrinthos",
    "mareLamentorum",
    "ultimaThule",
    "elpis",
    "unnamedIsland",
  ],
  dawntrail: [
    "tuliyollal",
    "urqopacha",
    "kozamauka",
    "yakTel",
    "solutionNine",
    "shaaloani",
    "heritageFound",
    "livingMemory",
    "sinusArdorum",
  ],
};
